export const GET_DEFAULT_POSTS = "GET_DEFAULT_POSTS";
export const GET_DEFAULT_POSTS_SUCCESS = "GET_DEFAULT_POSTS_SUCCESS";

export const GET_POSTS_BY_PAGE = "GET_POSTS_BY_PAGE";
export const GET_POSTS_BY_PAGE_SUCCESS = "GET_POSTS_BY_PAGE_SUCCESS";

export const SELECT_SINGLE_POST = "SELECT_SINGLE_POST";
export const SELECT_SINGLE_POST_SUCCESS = "SELECT_SINGLE_POST_SUCCESS";

export const CHANGE_FONTSIZE = "CHANGE_FONTSIZE";
export const CHANGE_FONTSIZE_SUCCESS = "CHANGE_FONTSIZE_SUCCESS";

export const GET_ERROR = "GET_ERROR";
